		</div>


<div class="footer container_16">
	© Copyright 1995 - 2009 Fo Guang Shan Melbourne. All rights reserved.</div>
<div class="footer container_16">
	版權所有：墨爾本佛光山 www.ibcv.org.au</div>
<div class="footer container_16">
	電話：61-3-9314 5147&nbsp;&nbsp;&nbsp;&nbsp;傳真：61-3-9314 2006</div>
<div class="footer container_16">
	Email:ibcv@fgs.org.au
</div>

	</body>

	</html>
	</div>
</body>

</html>