<div class="grid_4 right_col">
	<img src="img/xinyun-heading.png">
	<div class="content">
		<p>
			<b>啟示:</b>
		</p>
		<p>人若自大，其實正顯示自己的無知
		人能謙虛，其實正表示自己的無求</p>
	</div>
	<img src="img/zuixin-heading.png" />
	<div class="content">
		<a href="img/photo/poster/cny2011.jpg" rel="lightbox-cats1" style="width:860px;height:608px;padding-top:50px;">
			<img src="img/photo/poster/cny2011sml.jpg" width="210px" height="148px">
		</a>


		<br />
	</div>
	
</div>